### ISSUE TITLE
你好，我使用koolshare-v2ray-x64插件全局模式 和 大陆白名单都OK，但是GFW模式就不能翻墙了

### ISSUE THREAD

**Issue by youwei5683** [acgpiano/koolshare-v2ray-x64#1]
你好，我使用koolshare-v2ray-x64插件全局模式 和 大陆白名单都OK，但是GFW模式就不能翻墙了 请问你那边有没有同样的问题

**Comment by acgpiano** [comment]
我这边是好的，你可以看看你的规则管理里面有没有规则，我只是修改了原插件的更新，其他的技术问题我也不知道了

**Comment by youzi488** [comment]
规则，国内域名没有版本号，不知道是不是这个原因

**Comment by youzi488** [comment]
我下了一个老版本，2.3.7的，登录进入路由器koolshare/v2ray，将这个目录下的文件进行了替换，可以用GFW模式了

**Comment by acgpiano** [comment]
@737712963 @youwei5683 
现在更新了规则源，可以尝试下看解决问题了没
