### ISSUE TITLE
你好，能不能修改一下规则更新地址并重新打包？

### ISSUE THREAD

**Issue by crazyshitass** [acgpiano/koolshare-v2ray-x64#3]
这里（https://github.com/qxzg/Actions）有人做了新的自动更新fancyss规则的地址，能否测试和打包更新一下？原版的3个月才更新规则，实在是不方便。

url_main="https://raw.githubusercontent.com/hq450/fancyss/master/rules"改为
url_main="https://raw.githubusercontent.com/qxzg/Actions/master/fancyss_rules"

**Comment by acgpiano** [comment]
感谢，已更新该源
