### ISSUE TITLE
离线安装包 解压错误，错误代码：1！

### ISSUE THREAD

**Issue by yanghuan** [acgpiano/koolshare-v2ray-x64#4]
我安装时，总是报以下错误，能帮忙解答下吗（已经输入解除系统安装限制的命令）

【2021年03月29日 09:51:10】: ====================== step 1 ===========================
【2021年03月29日 09:51:10】: 开启软件离线安装！
【2021年03月29日 09:51:10】: /tmp/upload目录下检测到上传的离线安装包v2ray_4.35.1.tar.gz，大小：3.5M
【2021年03月29日 09:51:10】: 尝试解压离线安装包离线安装包
【2021年03月29日 09:51:10】: 解压错误，错误代码：1！
【2021年03月29日 09:51:10】: 估计是错误或者不完整的的离线安装包！
【2021年03月29日 09:51:10】: 删除相关文件并退出...
【2021年03月29日 09:51:10】: ======================== end ============================

**Comment by acgpiano** [comment]
建议挂代理之后去release界面重新下载，安装包正确的大小是12.1M，你这个明显是安装包没下载全。
原因有可能就是网络原因导致下载不完整
